Numpy & Pandas Introduction

In [11]:
import numpy as np
np.array([1,2,3])
array_1 = np.array([[123],[456]])
array_1

array([[123],
       [456]])

In [18]:
array_2 = np.array([[1,2,3],[4,5,6],['a','b','c']])
array_2
import numpy as np
array_2

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['a', 'b', 'c']], dtype='<U11')

Array.shape

In [19]:
array_2.shape

(3, 3)

In [13]:
array_1

array([[123],
       [456]])

In [19]:
array_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
array_2[0,2]

3

In [21]:
print(array_1.min())
print(array_1.max())

123
456


Pandas

In [25]:
import pandas as pd

In [30]:
markers = ['a','b','c']
list_1 = [12,24,36]
array_1 = np.array([15,30,45])
dict_1 = {'d':20,'e':40,'f':60}
pd.Series(data = list_1, index=markers)

a    12
b    24
c    36
dtype: int64

In [32]:
pd.Series(dict_1)

d    20
e    40
f    60
dtype: int64

In [34]:
gift_shop_salesQ1 = pd.Series(data=[300,550,240,180],index = ['magnets',
                                                             'Snacks',
                                                             'Handbags',
                                                             'coasters'])
gift_shop_salesQ1

magnets     300
Snacks      550
Handbags    240
coasters    180
dtype: int64

In [28]:
gift_shop_salesQ2 = pd.Series([480,530,360,40],index=['magnets',
                                                    'coasters',
                                                    'Handbags',
                                                    'Snacks'])
gift_shop_salesQ2

magnets     480
coasters    530
Handbags    360
Snacks       40
dtype: int64

In [26]:
gift_shop_salesQ3 = pd.Series([40,342,330,200],index=['magnets',
                                                     'coasters',
                                                     'Handbags',
                                                     'postcards'])
gift_shop_salesQ3

magnets       40
coasters     342
Handbags     330
postcards    200
dtype: int64

In [35]:
gift_shop_salesQ1+gift_shop_salesQ2

Handbags    600
Snacks      590
coasters    710
magnets     780
dtype: int64

In [47]:
frames = np.array([[1,2,3,4,5,6,7,8,9],[4,5,6,7,8,9,10,11,12],[4,5,6,7,8,9,10,11,12],
                   [6,10,11,12,13,14,15,12,16],[2,3,2,4,2,3,6,7,8],[1,2,3,5,6,7,8,9,10],
                   [2,4,3,5,6,7,8,9,8],[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]])
frames

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 6, 10, 11, 12, 13, 14, 15, 12, 16],
       [ 2,  3,  2,  4,  2,  3,  6,  7,  8],
       [ 1,  2,  3,  5,  6,  7,  8,  9, 10],
       [ 2,  4,  3,  5,  6,  7,  8,  9,  8],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [50]:
Tittle = print('accounting Department')
Rows = ['A','B','C','D','E','F','G','H','I']
Columns = ['P','H','O','Q','R','S','X','Y','Z']
dataframe_1 = pd.DataFrame(frames,Rows,Columns)
dataframe_1

accounting Department


P   H   O   Q   R   S   X   Y   Z
A  1   2   3   4   5   6   7   8   9
B  4   5   6   7   8   9  10  11  12
C  4   5   6   7   8   9  10  11  12
D  6  10  11  12  13  14  15  12  16
E  2   3   2   4   2   3   6   7   8
F  1   2   3   5   6   7   8   9  10
G  2   4   3   5   6   7   8   9   8
H  1   2   3   4   5   6   7   8   9
I  1   2   3   4   5   6   7   8   9

In [7]:
dictionary_2 = {'Grade':['A','A','B','C','C'],
               'Price':[125,236,300,472,600],
               'City':['Nrbi','Nyeri','Kara','Msa','Meru']}
dictionary_2
dataframe_2 = pd.DataFrame(dictionary_2)
dataframe_2

Grade  Price   City
0     A    125   Nrbi
1     A    236  Nyeri
2     B    300   Kara
3     C    472    Msa
4     C    600   Meru

In [13]:
import pandas as pd
import numpy as np
array_3 = np.arange(30)
array_3
array_4 = np.arange(3,7)
array_4

array([3, 4, 5, 6])

In [17]:
np.arange(1,10,2)
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [27]:
np.random.rand(10)
np.random.randint(10,20)
np.random.randint(1,100,(4,5))

array([[ 9, 44,  4, 29, 47],
       [49,  5, 79, 92,  4],
       [40, 79, 60, 57, 63],
       [94, 88,  2, 92, 92]])

In [1]:
import pandas as pd
import pandas_DataReader.data as pds

ModuleNotFoundError: No module named 'pandas_DataReader'

In [7]:
pdr.DataReader('005930','naver','2022-01-01','2022-01-31')

NameError: name 'pdr' is not defined

In [ ]:
conda install -c anaconda pandas-datareader